package sudoku;

import java.awt.TextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import sudoku.Sudoku.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class SudokuGUI extends javax.swing.JFrame {

    /**
     * Creates new form SudokuGUI2
     */
    public SudokuGUI() {
        initComponents();
    }
    
    TextField casillaActual;
    public int row, col;
    public int[][] matriz = new int[9][9];
    Sudoku sudoku = new Sudoku();
    
    public void setCell(int value){
        matriz[row][col] = value;
        casillaActual.setText(Integer.toString(value));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla1l1 = new java.awt.TextField();
        casilla1l2 = new java.awt.TextField();
        casilla1l3 = new java.awt.TextField();
        casilla1l4 = new java.awt.TextField();
        casilla1l5 = new java.awt.TextField();
        casilla1l6 = new java.awt.TextField();
        casilla1l7 = new java.awt.TextField();
        casilla1l8 = new java.awt.TextField();
        casilla1l9 = new java.awt.TextField();
        casilla2l1 = new java.awt.TextField();
        casilla2l2 = new java.awt.TextField();
        casilla2l3 = new java.awt.TextField();
        casilla2l4 = new java.awt.TextField();
        casilla2l5 = new java.awt.TextField();
        casilla2l6 = new java.awt.TextField();
        casilla2l7 = new java.awt.TextField();
        casilla2l8 = new java.awt.TextField();
        casilla2l9 = new java.awt.TextField();
        casilla3l1 = new java.awt.TextField();
        casilla3l2 = new java.awt.TextField();
        casilla3l3 = new java.awt.TextField();
        casilla3l4 = new java.awt.TextField();
        casilla3l5 = new java.awt.TextField();
        casilla3l6 = new java.awt.TextField();
        casilla3l7 = new java.awt.TextField();
        casilla3l8 = new java.awt.TextField();
        casilla3l9 = new java.awt.TextField();
        casilla4l1 = new java.awt.TextField();
        casilla4l2 = new java.awt.TextField();
        casilla4l3 = new java.awt.TextField();
        casilla4l4 = new java.awt.TextField();
        casilla4l5 = new java.awt.TextField();
        casilla4l6 = new java.awt.TextField();
        casilla4l7 = new java.awt.TextField();
        casilla4l8 = new java.awt.TextField();
        casilla4l9 = new java.awt.TextField();
        casilla5l1 = new java.awt.TextField();
        casilla5l2 = new java.awt.TextField();
        casilla5l3 = new java.awt.TextField();
        casilla5l4 = new java.awt.TextField();
        casilla5l5 = new java.awt.TextField();
        casilla5l6 = new java.awt.TextField();
        casilla5l7 = new java.awt.TextField();
        casilla5l8 = new java.awt.TextField();
        casilla5l9 = new java.awt.TextField();
        casilla6l1 = new java.awt.TextField();
        casilla6l2 = new java.awt.TextField();
        casilla6l3 = new java.awt.TextField();
        casilla6l4 = new java.awt.TextField();
        casilla6l5 = new java.awt.TextField();
        casilla6l6 = new java.awt.TextField();
        casilla6l7 = new java.awt.TextField();
        casilla6l8 = new java.awt.TextField();
        casilla6l9 = new java.awt.TextField();
        casilla7l1 = new java.awt.TextField();
        casilla7l2 = new java.awt.TextField();
        casilla7l3 = new java.awt.TextField();
        casilla7l4 = new java.awt.TextField();
        casilla7l5 = new java.awt.TextField();
        casilla7l6 = new java.awt.TextField();
        casilla7l7 = new java.awt.TextField();
        casilla7l8 = new java.awt.TextField();
        casilla7l9 = new java.awt.TextField();
        casilla8l1 = new java.awt.TextField();
        casilla8l2 = new java.awt.TextField();
        casilla8l3 = new java.awt.TextField();
        casilla8l4 = new java.awt.TextField();
        casilla8l5 = new java.awt.TextField();
        casilla8l6 = new java.awt.TextField();
        casilla8l7 = new java.awt.TextField();
        casilla8l8 = new java.awt.TextField();
        casilla8l9 = new java.awt.TextField();
        casilla9l1 = new java.awt.TextField();
        casilla9l2 = new java.awt.TextField();
        casilla9l3 = new java.awt.TextField();
        casilla9l4 = new java.awt.TextField();
        casilla9l5 = new java.awt.TextField();
        casilla9l6 = new java.awt.TextField();
        casilla9l7 = new java.awt.TextField();
        casilla9l8 = new java.awt.TextField();
        casilla9l9 = new java.awt.TextField();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonResolver = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        casillaResultado = new javax.swing.JTextField();
        tituloSudoku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        casilla1l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l1.setPreferredSize(new java.awt.Dimension(30, 30));
        casilla1l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla1l1MouseClicked(evt);
            }
        });

        casilla1l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l2.setPreferredSize(new java.awt.Dimension(30, 30));
        casilla1l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla1l2MouseClicked(evt);
            }
        });

        casilla1l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla1l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla1l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla1l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla2l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla2l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla2l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l2.setPreferredSize(new java.awt.Dimension(30, 30));
        casilla3l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla3l2MouseClicked(evt);
            }
        });

        casilla3l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l3.setPreferredSize(new java.awt.Dimension(30, 30));
        casilla3l3.setText(" ");
        casilla3l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla3l3MouseClicked(evt);
            }
        });

        casilla3l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla3l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla3l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla3l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla4l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla4l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla4l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla5l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla5l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla5l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla6l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla6l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla6l9.setPreferredSize(new java.awt.Dimension(30, 30));
        casilla6l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla6l9MouseClicked(evt);
            }
        });

        casilla7l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla7l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla7l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla7l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla8l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla8l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla8l9.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l1.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l2.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l3.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l4.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l5.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l6.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l7.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l8.setPreferredSize(new java.awt.Dimension(30, 30));

        casilla9l9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        casilla9l9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        casilla9l9.setPreferredSize(new java.awt.Dimension(30, 30));

        boton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton1.setText("1");
        boton1.setPreferredSize(new java.awt.Dimension(45, 45));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton2.setText("2");
        boton2.setPreferredSize(new java.awt.Dimension(45, 45));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton3.setText("3");
        boton3.setPreferredSize(new java.awt.Dimension(45, 45));

        boton4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton4.setText("4");
        boton4.setPreferredSize(new java.awt.Dimension(45, 45));

        boton5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton5.setText("5");
        boton5.setPreferredSize(new java.awt.Dimension(45, 45));

        boton6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton6.setText("6");
        boton6.setPreferredSize(new java.awt.Dimension(45, 45));

        boton7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton7.setText("7");
        boton7.setPreferredSize(new java.awt.Dimension(45, 45));
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton8.setText("8");
        boton8.setPreferredSize(new java.awt.Dimension(45, 45));

        boton9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        boton9.setText("9");
        boton9.setPreferredSize(new java.awt.Dimension(45, 45));

        botonResolver.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        botonResolver.setText("Resolver");
        botonResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResolverActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        casillaResultado.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N

        tituloSudoku.setFont(new java.awt.Font("Tempus Sans ITC", 0, 30)); // NOI18N
        tituloSudoku.setText("Sudoku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla1l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla4l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla7l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla4l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla7l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla1l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla1l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla1l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla4l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla4l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla7l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla7l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla2l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla5l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla8l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla5l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla8l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla2l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla2l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla2l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla5l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla5l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla8l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla8l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla9l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla9l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla9l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casilla9l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla3l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla3l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla3l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla3l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla6l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla6l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla6l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casilla6l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botonResolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(casillaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tituloSudoku, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla1l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla1l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla1l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla1l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla2l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla3l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla4l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla4l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casilla4l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla4l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla5l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla6l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloSudoku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botonResolver)
                                        .addGap(30, 30, 30))
                                    .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(30, 30, 30))
                            .addComponent(casillaResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla7l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla7l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla7l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        setCell(1);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {                                                                                            
        setCell(2);
    }                                                                                    
    
    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {                                                                                                                    
        setCell(3);
    }                                                                                 
    
    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {                                                                              
        setCell(4);
    }                                          
    
    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {                                                                              
        setCell(5);
    }                                              
    
    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {                                                                              
        setCell(6);
    }                                              
    
    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        setCell(7);
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {                                                                              
        setCell(8);
    }                                              
    
    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {                                                                              
        setCell(9);
    }                                              

    private void casilla1l1MouseClicked(java.awt.event.MouseEvent evt) {
        row=0;
        col=0;
        casillaActual=casilla1l1;
    }

    private void casilla1l2MouseClicked(java.awt.event.MouseEvent evt) {
        row=0;
        col=1;
        casillaActual=casilla1l2;
    }

    private void casilla1l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=2;
        casillaActual=casilla1l3;
    }     
    
    private void casilla1l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=3;
        casillaActual=casilla1l4;
    }    
    
    private void casilla1l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=4;
        casillaActual=casilla1l5;
    }     

    private void casilla1l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=5;
        casillaActual=casilla1l6;
    } 

    private void casilla1l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=6;
        casillaActual=casilla1l7;
    }     
    
    private void casilla1l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=7;
        casillaActual=casilla1l8;
    }   
    
    private void casilla1l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=0;
        col=8;
        casillaActual=casilla1l9;
    }        
    
    
    private void casilla2l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=0;
        casillaActual=casilla2l1;
    }                                       


    private void casilla2l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=1;
        casillaActual=casilla2l2;
    }                                       

    private void casilla2l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=2;
        casillaActual=casilla2l3;
    }     
    
    private void casilla2l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=3;
        casillaActual=casilla2l4;
    }    
    
    private void casilla2l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=4;
        casillaActual=casilla2l5;
    }     

    private void casilla2l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=5;
        casillaActual=casilla2l6;
    } 

    private void casilla2l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=6;
        casillaActual=casilla2l7;
    }     
    
    private void casilla2l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=7;
        casillaActual=casilla2l8;
    }   
    
    private void casilla2l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=1;
        col=8;
        casillaActual=casilla2l9;
    }       
    
    
    private void casilla3l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=0;
        casillaActual=casilla3l1;
    }                                       


    private void casilla3l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=1;
        casillaActual=casilla3l2;
    }                                       

    private void casilla3l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=2;
        casillaActual=casilla3l3;
    }     
    
    private void casilla3l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=3;
        casillaActual=casilla3l4;
    }    
    
    private void casilla3l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=4;
        casillaActual=casilla3l5;
    }     

    private void casilla3l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=5;
        casillaActual=casilla3l6;
    } 

    private void casilla3l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=6;
        casillaActual=casilla3l7;
    }     
    
    private void casilla3l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=7;
        casillaActual=casilla3l8;
    }   
    
    private void casilla3l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=2;
        col=8;
        casillaActual=casilla3l9;
    }       
    
    
    private void casilla4l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=0;
        casillaActual=casilla4l1;
    }                                       


    private void casilla4l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=1;
        casillaActual=casilla4l2;
    }                                       

    private void casilla4l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=2;
        casillaActual=casilla4l3;
    }     
    
    private void casilla4l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=3;
        casillaActual=casilla4l4;
    }    
    
    private void casilla4l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=4;
        casillaActual=casilla4l5;
    }     

    private void casilla4l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=5;
        casillaActual=casilla4l6;
    } 

    private void casilla4l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=6;
        casillaActual=casilla4l7;
    }     
    
    private void casilla4l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=7;
        casillaActual=casilla4l8;
    }   
    
    private void casilla4l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=3;
        col=8;
        casillaActual=casilla4l9;
    }      
    
    
    private void casilla5l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=0;
        casillaActual=casilla5l1;
    }                                       


    private void casilla5l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=1;
        casillaActual=casilla5l2;
    }                                       

    private void casilla5l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=2;
        casillaActual=casilla5l3;
    }     
    
    private void casilla5l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=3;
        casillaActual=casilla5l4;
    }    
    
    private void casilla5l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=4;
        casillaActual=casilla5l5;
    }     

    private void casilla5l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=5;
        casillaActual=casilla5l6;
    } 

    private void casilla5l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=6;
        casillaActual=casilla5l7;
    }     
    
    private void casilla5l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=7;
        casillaActual=casilla5l8;
    }   
    
    private void casilla5l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=4;
        col=8;
        casillaActual=casilla5l9;
    }        
    
    
    private void casilla6l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=0;
        casillaActual=casilla6l1;
    }                                       


    private void casilla6l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=1;
        casillaActual=casilla6l2;
    }                                       

    private void casilla6l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=2;
        casillaActual=casilla6l3;
    }     
    
    private void casilla6l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=3;
        casillaActual=casilla6l4;
    }    
    
    private void casilla6l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=4;
        casillaActual=casilla6l5;
    }     

    private void casilla6l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=5;
        casillaActual=casilla6l6;
    } 

    private void casilla6l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=6;
        casillaActual=casilla6l7;
    }     
    
    private void casilla6l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=7;
        casillaActual=casilla6l8;
    }   
    
    private void casilla6l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=5;
        col=8;
        casillaActual=casilla6l9;
    }        
    
    
    private void casilla7l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=0;
        casillaActual=casilla7l1;
    }                                       


    private void casilla7l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=1;
        casillaActual=casilla7l2;
    }                                       

    private void casilla7l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=2;
        casillaActual=casilla7l3;
    }     
    
    private void casilla7l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=3;
        casillaActual=casilla7l4;
    }    
    
    private void casilla7l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=4;
        casillaActual=casilla7l5;
    }     

    private void casilla7l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=5;
        casillaActual=casilla7l6;
    } 

    private void casilla7l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=6;
        casillaActual=casilla7l7;
    }     
    
    private void casilla7l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=7;
        casillaActual=casilla7l8;
    }   
    
    private void casilla7l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=6;
        col=8;
        casillaActual=casilla7l9;
    }        


    private void casilla8l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=0;
        casillaActual=casilla8l1;
    }                                       


    private void casilla8l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=1;
        casillaActual=casilla8l2;
    }                                       

    private void casilla8l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=2;
        casillaActual=casilla8l3;
    }     
    
    private void casilla8l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=3;
        casillaActual=casilla8l4;
    }    
    
    private void casilla8l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=4;
        casillaActual=casilla8l5;
    }     

    private void casilla8l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=5;
        casillaActual=casilla8l6;
    } 

    private void casilla8l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=6;
        casillaActual=casilla8l7;
    }     
    
    private void casilla8l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=7;
        casillaActual=casilla8l8;
    }   
    
    private void casilla8l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=7;
        col=8;
        casillaActual=casilla8l9;
    }        


    private void casilla9l1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=0;
        casillaActual=casilla9l1;
    }                                       


    private void casilla9l2MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=1;
        casillaActual=casilla9l2;
    }                                       

    private void casilla9l3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=2;
        casillaActual=casilla9l3;
    }     
    
    private void casilla9l4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=3;
        casillaActual=casilla9l4;
    }    
    
    private void casilla9l5MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=4;
        casillaActual=casilla9l5;
    }     

    private void casilla9l6MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=5;
        casillaActual=casilla9l6;
    } 

    private void casilla9l7MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=6;
        casillaActual=casilla9l7;
    }     
    
    private void casilla9l8MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=7;
        casillaActual=casilla9l8;
    }   
    
    private void casilla9l9MouseClicked(java.awt.event.MouseEvent evt) {                                        
        row=8;
        col=8;
        casillaActual=casilla9l9;
    }        

    private void botonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResolverActionPerformed
        try {
            sudoku.setMatriz(matriz);
        } catch (Exception ex) {
            Logger.getLogger(SudokuGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sudoku.resuelve();
    }//GEN-LAST:event_botonResolverActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        matriz = new int[9][9];
    }//GEN-LAST:event_botonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonResolver;
    private java.awt.TextField casilla1l1;
    private java.awt.TextField casilla1l2;
    private java.awt.TextField casilla1l3;
    private java.awt.TextField casilla1l4;
    private java.awt.TextField casilla1l5;
    private java.awt.TextField casilla1l6;
    private java.awt.TextField casilla1l7;
    private java.awt.TextField casilla1l8;
    private java.awt.TextField casilla1l9;
    private java.awt.TextField casilla2l1;
    private java.awt.TextField casilla2l2;
    private java.awt.TextField casilla2l3;
    private java.awt.TextField casilla2l4;
    private java.awt.TextField casilla2l5;
    private java.awt.TextField casilla2l6;
    private java.awt.TextField casilla2l7;
    private java.awt.TextField casilla2l8;
    private java.awt.TextField casilla2l9;
    private java.awt.TextField casilla3l1;
    private java.awt.TextField casilla3l2;
    private java.awt.TextField casilla3l3;
    private java.awt.TextField casilla3l4;
    private java.awt.TextField casilla3l5;
    private java.awt.TextField casilla3l6;
    private java.awt.TextField casilla3l7;
    private java.awt.TextField casilla3l8;
    private java.awt.TextField casilla3l9;
    private java.awt.TextField casilla4l1;
    private java.awt.TextField casilla4l2;
    private java.awt.TextField casilla4l3;
    private java.awt.TextField casilla4l4;
    private java.awt.TextField casilla4l5;
    private java.awt.TextField casilla4l6;
    private java.awt.TextField casilla4l7;
    private java.awt.TextField casilla4l8;
    private java.awt.TextField casilla4l9;
    private java.awt.TextField casilla5l1;
    private java.awt.TextField casilla5l2;
    private java.awt.TextField casilla5l3;
    private java.awt.TextField casilla5l4;
    private java.awt.TextField casilla5l5;
    private java.awt.TextField casilla5l6;
    private java.awt.TextField casilla5l7;
    private java.awt.TextField casilla5l8;
    private java.awt.TextField casilla5l9;
    private java.awt.TextField casilla6l1;
    private java.awt.TextField casilla6l2;
    private java.awt.TextField casilla6l3;
    private java.awt.TextField casilla6l4;
    private java.awt.TextField casilla6l5;
    private java.awt.TextField casilla6l6;
    private java.awt.TextField casilla6l7;
    private java.awt.TextField casilla6l8;
    private java.awt.TextField casilla6l9;
    private java.awt.TextField casilla7l1;
    private java.awt.TextField casilla7l2;
    private java.awt.TextField casilla7l3;
    private java.awt.TextField casilla7l4;
    private java.awt.TextField casilla7l5;
    private java.awt.TextField casilla7l6;
    private java.awt.TextField casilla7l7;
    private java.awt.TextField casilla7l8;
    private java.awt.TextField casilla7l9;
    private java.awt.TextField casilla8l1;
    private java.awt.TextField casilla8l2;
    private java.awt.TextField casilla8l3;
    private java.awt.TextField casilla8l4;
    private java.awt.TextField casilla8l5;
    private java.awt.TextField casilla8l6;
    private java.awt.TextField casilla8l7;
    private java.awt.TextField casilla8l8;
    private java.awt.TextField casilla8l9;
    private java.awt.TextField casilla9l1;
    private java.awt.TextField casilla9l2;
    private java.awt.TextField casilla9l3;
    private java.awt.TextField casilla9l4;
    private java.awt.TextField casilla9l5;
    private java.awt.TextField casilla9l6;
    private java.awt.TextField casilla9l7;
    private java.awt.TextField casilla9l8;
    private java.awt.TextField casilla9l9;
    private javax.swing.JTextField casillaResultado;
    private javax.swing.JLabel tituloSudoku;
    // End of variables declaration//GEN-END:variables
}
